# Generated by Django 5.2.3 on 2025-06-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='company',
        ),
        migrations.RemoveField(
            model_name='record',
            name='county',
        ),
        migrations.RemoveField(
            model_name='record',
            name='disposal_method',
        ),
        migrations.RemoveField(
            model_name='record',
            name='disposed_quantity',
        ),
        migrations.RemoveField(
            model_name='record',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='record',
            name='generated_quantity',
        ),
        migrations.RemoveField(
            model_name='record',
            name='generator',
        ),
        migrations.RemoveField(
            model_name='record',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='record',
            name='recycled_quantity',
        ),
        migrations.RemoveField(
            model_name='record',
            name='recycling_method',
        ),
        migrations.RemoveField(
            model_name='record',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='record',
            name='type_of_waste',
        ),
        migrations.RemoveField(
            model_name='record',
            name='waste_code',
        ),
        migrations.RemoveField(
            model_name='record',
            name='waste_company',
        ),
        migrations.RemoveField(
            model_name='record',
            name='waste_description',
        ),
        migrations.RemoveField(
            model_name='record',
            name='waste_name',
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='source_panchayat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='waste_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
