# Generated by Django 5.2.3 on 2025-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_record_company_remove_record_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
